modLoader="javafml"
license="${mod_license}"
loaderVersion="${neoforge_loader_version_range}"
issueTrackerURL="${mod_issues_url}"
displayURL="${mod_page_url}"
logoFile="${mod_id}_logo.png"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_display_name}"
	authors="${mod_authors}"
    description="${mod_description}"

[[dependencies.${mod_id}]]
    modId="neoforge"
    required=true
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="glitchcore"
    required=true
    versionRange="[${glitchcore_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="terrablender"
    required=true
    versionRange="[${terrablender_version},)"
    ordering="AFTER"
    side="BOTH"